"""Default configuration for lime-audit runs."""

LIME_NUM_SAMPLES = 300
LIME_NUM_FEATURES = 10
LIME_CLASS_NAMES = ["negative", "positive"]

RANDOM_SEEDS = [42, 123, 456, 789, 1024]
CANONICAL_SEED = 42

TOP_K_FOR_JACCARD = 5

STABILITY_THRESHOLD_JACCARD = 0.6
STABILITY_THRESHOLD_KENDALL = 0.5
FAITHFULNESS_THRESHOLD_DIRECTION = 0.7
